[package]
name = "rayo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.9.0"
rayon = "1.7.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4
